-- POPKADA SUPABASE DATABASE
-- Run this in Supabase Dashboard > SQL Editor.

create table if not exists public.feedback (
  id bigint generated by default as identity primary key,
  rating smallint null,
  comment varchar(500) not null default '',
  status text not null default 'new',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint feedback_rating_check check (rating is null or rating between 1 and 5),
  constraint feedback_status_check check (status in ('new', 'read', 'resolved'))
);

create or replace function public.set_feedback_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists feedback_updated_at on public.feedback;
create trigger feedback_updated_at
before update on public.feedback
for each row execute function public.set_feedback_updated_at();

-- Enable Row Level Security.
alter table public.feedback enable row level security;

-- Remove old policies if this script is run again.
drop policy if exists "Public can submit feedback" on public.feedback;
drop policy if exists "Public can view feedback" on public.feedback;
drop policy if exists "Public can update feedback status" on public.feedback;

-- This project currently has no admin login, so the browser uses the anon/publishable key.
-- These policies make the demo work from both index.html and admin.html.
-- For production, add Supabase Auth and restrict SELECT/UPDATE to authenticated admins.
create policy "Public can submit feedback"
on public.feedback
for insert
to anon
with check (
  (rating is null or rating between 1 and 5)
  and char_length(comment) <= 500
  and status = 'new'
);

create policy "Public can view feedback"
on public.feedback
for select
to anon
using (true);

create policy "Public can update feedback status"
on public.feedback
for update
to anon
using (true)
with check (status in ('new', 'read', 'resolved'));

-- Grant only the operations used by the current browser-based project.
grant select, insert, update on public.feedback to anon;
